# -*- coding: utf-8 -*-
"""Movie_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s-RLkH6N4LGRI3NWhPBY1CdKF89OVH_
"""

import numpy as np
import pandas as pd
import ast
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

keywords = pd.read_csv('/content/keywords.csv')
movies = pd.read_csv('/content/movies_metadata.csv', low_memory=False)

movies = movies.sample(5000, random_state=42)
movies.head(10)

credits = pd.read_csv('/content/credits.csv')

plt.figure(figsize=(8,5))
sns.histplot(movies['vote_average'], bins=20, kde=True)
plt.title('Distribution of Movie Ratings (Vote Average)')
plt.xlabel('Vote Average')
plt.ylabel('Count')
plt.show()

popular_movies = movies.sort_values('popularity', ascending=False).head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=popular_movies['popularity'], y=popular_movies['title'])
plt.title('Top 10 Most Popular Movies')
plt.xlabel('Popularity Score')
plt.ylabel('Movie Title')
plt.show()

for col in ['popularity', 'vote_average', 'vote_count']:
    movies[col] = pd.to_numeric(movies[col], errors='coerce')

movies.dropna(subset=['popularity', 'vote_average', 'vote_count'], inplace=True)

numeric_cols = ['popularity', 'vote_average', 'vote_count']
correlation_matrix = movies[numeric_cols].corr()

plt.figure(figsize=(6,5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Movie Features')
plt.show()

movies = movies[['id', 'title', 'overview', 'genres', 'popularity', 'vote_average', 'vote_count']]

movies['id'] = pd.to_numeric(movies['id'], errors='coerce')
credits['id'] = pd.to_numeric(credits['id'], errors='coerce')
keywords['id'] = pd.to_numeric(keywords['id'], errors='coerce')

movies.dropna(subset=['id', 'overview'], inplace=True)

movies = movies.merge(credits, on='id')
movies = movies.merge(keywords, on='id')

def get_director(crew_text):
    try:
        crew_list = ast.literal_eval(crew_text)
        for person in crew_list:
            if person.get('job') == 'Director':
                return person.get('name')
        return ''
    except:
        return ''

movies['director'] = movies['crew'].apply(get_director)

def extract_names(text):
  try:
    return ' '.join([i['name'] for i in ast.literal_eval(text)])
  except:
    return ''
movies['genres'] = movies['genres'].apply(extract_names)
movies['keywords'] = movies['keywords'].apply(extract_names)
movies['cast'] = movies['cast'].apply(extract_names)
movies['crew'] = movies['crew'].apply(lambda x: ' '.join([i['name'] for i in ast.literal_eval(x) if i['job'] == 'Director']) if isinstance(x, str) else '')

movies['combined_features'] = (movies['overview'] + ' ' +
                               movies['genres'] + ' ' +
                               movies['keywords'] + ' ' +
                               movies['cast'] + ' ' +movies['crew']
)

vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = vectorizer.fit_transform(movies['combined_features'])

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

movies.reset_index(drop=True, inplace=True)

def recommend_movie(title, num_recommendations=5):
    if title not in movies['title'].values:
        return f"Movie '{title}' not found in dataset."
    idx = movies[movies['title'] == title].index[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:num_recommendations+1]
    movie_indices = [i[0] for i in sim_scores]
    return movies[['title', 'vote_average']].iloc[movie_indices]

print("Recommendations for 'THE SEA CHASE':")
print(recommend_movie('the sea chase'))

movie_name = input("Enter a movie name: ")
print(recommend_movie(movie_name))